### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by Samitti**
I have completed the Milestone: friendships v1. Please kindly review my code.

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello coders,

You did a really nice introduction into this milestone.
There are some missed requirements that should be completed in order to move forward.

1. It's asked, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) that, posts timeline includes posts written by logged-in user and their friends.
But in your case, any user's posts are included in any timeline.

2. From the users list, it's not possible to reach to the user profile. The link `See profile` is not available. Why?
The only way to access to user profile is through the timeline.

Also, it's requested, [read it here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) that, there should be a button to invite user to friendship on users list page and on single user page. 
There is no button on the user page as you could see from this screenshot
Screenshot at 2020-07-07 21:34:41

3- Please, write tests. Unit test and Integration tests. 
I suggest you use, in addition to **shoulda-matchers**, **faker** and **factory**


Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Comment by Samitti** [comment]
I have made the changes required from the previous review, please kindly review my code again.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, but there are a few more things required. 
### General
- [ ] I cant see linter checks, let's fix that 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Samitti** [comment]
I have fixed all the changes required, kindly please review my code.

**Pull request merged**
