### PR TITLE
Milestone 6 

### PR DESCRIPTION
**Pull request by Samitti**
I have implemented mutual friendship, please kindly review my code.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required 
Great work implementing two rows for mutual friendship :clap: 
We can make this feature even more better.

### REQUIRED
**User Model**
* We can define `friends` method in user model using queries instead of passing objects to the object memory. Since we have two rows for mutual friendship, we can find user's friends using `user_id` in the Friendship table. 
  ```ruby
  has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
  has_many :friends, through: :confirmed_friendships
  ```
* We can also define `pending_friends` using queries since database is designed to be more efficient the Ruby.
* Lastly, we can define `friend_resquests` using queries as follows
  ```ruby
  has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
  has_many :friend_requests, through: :inverted_friendships, source: :user
  ```
* We don't need `inverse_friends` method since we have two rows for mutual friendship.
  ```ruby
  def friend?(user)
      friends.include?(user)
   end
  ```
**After implementing the changes, submit another request another request for review.**

_Feel free to react out via slack for any issue or clarification._
**Happy Coding :computer: 
Simon Wathigo**

**Comment by Samitti** [comment]
I have made all the changes required, kindly please review my code.

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @Samitti     
#### Great Job so far, but there are a few more things required. 
### General
* [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
- [ ] KIndly delete all commented codes in `User` model. 
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Samitti** [comment]
I have made the changes required, please kindly review my code.

**Review by kobiyoyo — APPROVED** [review]
Hello @Samitti your project has been 
### Approved!!!
## Go ahead and merge

**Pull request merged**
